version: "3.8"

volumes:
  rabbitmq_data:

services:

  ####################################
  # Authentication: The Authentication Microservice   
  ####################################
  authentication:
    build: 
      context: ./authentication
      dockerfile: authentication.Dockerfile
    image: nichgoh/authentication:esd
    restart: always
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - DBNAME=user
      - DBUSER=root
      - DBPASS=
      - DBHOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq

  ###################################
  # Survey: The Survey microservice
  ###################################
  survey:
    build:
      context: ./
      dockerfile: survey.Dockerfile
    image: nichgoh/survey:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/survey_record
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  ###################################
  # Loyalty: The Loyalty microservice
  ###################################
  loyalty:
    build:
      context: ./
      dockerfile: loyalty.Dockerfile
    image: nichgoh/loyalty:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/loyalty_record
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ###################################
  # Reservation: The Reservation microservice
  ###################################
  reservation:
    build:
      context: ./
      dockerfile: reservation.Dockerfile
    image: nichgoh/reservation:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/reservation
      PYTHONUNBUFFERED: 1

  #################################################
  # Send Email: The Send Email microservice
  #################################################
  send_email:
    build:
      context: ./
      dockerfile: send_email.Dockerfile
    image: nichgoh/send_email:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      queue_name: reservation_confirmation
      PYTHONUNBUFFERED: 1

  ###############################################
  # Make Recommendation: The Make Recommendation microservice
  ###############################################
  make_recommendation:
    build:
      context: ./
      dockerfile: make_recommendation.Dockerfile
    image: nichgoh/make_recommendation:esd
    restart: always
    depends_on:
      - survey
      - authentication
    environment:
      survey_URL: http://survey:5004/survey
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5101"

  ###############################################
  # Make Reservation: The Make Reservation microservice
  ###############################################
  make_reservation:
    build:
      context: ./
      dockerfile: make_reservation.Dockerfile
    image: nichgoh/make_reservation:esd
    restart: always
    depends_on:
      - loyalty
      - reservation
      - send_email
      - authentication
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      loyalty_URL: http://loyalty:5001/loyalty_record
      reservation_URL: http://reservation:5000/reservation
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ###############################################
  # Display Analytics: The Display Analytics microservice
  ###############################################
  display_analytics:
    build:
      context: ./
      dockerfile: display_analytics.Dockerfile
    image: nichgoh/display_analytics:esd
    restart: always
    depends_on:
      - retrieve_data
      - authentication
    environment:
      retrieve_data_URL: "http://retrieve_data:5003/data"
      PYTHONUNBUFFERED: 1
    ports:
      - "4020:4020"

  ###############################################
  # Retrieve Data: The Retrieve Data microservice
  ###############################################
  retrieve_data:
    build:
      context: ./
      dockerfile: retrieve_data.Dockerfile
    image: nichgoh/retrieve_data:esd
    restart: always
    depends_on:
      - reservation
      - authentication
    environment:
      reservation_URL: http://reservation:5000/reservation
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ##############################################
  #Create Restaurant: The Create Restaurant microservice
  ##############################################
  create_restuarant:
    build:
      context: ./
      dockerfile: create_restaurant.Dockerfile
    image: nichgoh/create_restaurant:esd
    restart: always
    depends_on:
      - authentication
    environment:
      authentication_URL: http://authentication:4000/
      PYTHONUNBUFFERED: 1
    ports:
      - "4001:4001"